### ISSUE TITLE
Can declare Wildmen adventures wars on underground rulers as overground rulers

### ISSUE THREAD

**Issue by zeltron1** [CK3RealmsinExile/RealmsInExile#1165]
![Screenshot 2024-08-23 112305](https://github.com/user-attachments/assets/e7890212-e59e-41be-a843-23dbe43f1fa6)

**Comment by AerienA** [comment]
Fixed, can you confirm?

**Comment by zeltron1** [comment]
I can confirm this is not fixed

![Image](https://github.com/user-attachments/assets/287378a1-86c5-43b0-9932-5763e87fae89)

**Comment by Jaguaism** [comment]
<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/e5730c11-b58c-4d37-aa64-ed9eeb3bb6aa" />

<img width="1641" height="1079" alt="Image" src="https://github.com/user-attachments/assets/34c08ce0-ffa4-4f40-88f6-ac044b561311" />

Seems fixed now, Roaming Adventure doesnt show up for underground rulers.
