### ISSUE TITLE
Dreaming of Distant Land (Tibet)

### ISSUE THREAD

**Issue by StellaSAX** [CK3RealmsinExile/RealmsInExile#1207]
Reference to real region(Tibet) not removed
![20241110223915_1](https://github.com/user-attachments/assets/ce1b64f6-e705-4c6b-8f1b-ff9064609a6d)

**Comment by StellaSAX** [comment]
![20241111004840_1](https://github.com/user-attachments/assets/c936cd11-86f9-460e-ba17-2a64ad52d631)

**Comment by Jaco-Daan** [comment]
Pushed a fix. Please test and close if fixed

**Comment by StellaSAX** [comment]
Almost fixed, now we need the event to target our regions
![20241111110033_1](https://github.com/user-attachments/assets/9899dde6-75b0-4038-8660-a77a19f8d25e)

**Comment by Jaco-Daan** [comment]
This should be fixed. Confirm and close if fixed.

**Comment by StellaSAX** [comment]
Not quite fixed
![20241111112220_1](https://github.com/user-attachments/assets/3772f988-34c7-43cd-baef-d2e90ffac19a)

**Comment by Trigparmandil** [comment]
This is still an issue, but the event is prevented from firing
