### ISSUE TITLE
Randomly generated women can sometimes have beards despite game rule limitations

### ISSUE THREAD

**Issue by zeltron1** [CK3RealmsinExile/RealmsInExile#1284]
This is a global effect. I suspect this to be a broken trigger somewhere in the code. We should ideally fix this before the open beta as its going to spam reported otherwise given how easy it is to replicate and how big it is.

![Image](https://github.com/user-attachments/assets/46a04ca0-44c6-4624-8d19-0b5d3a6916fc)

**Comment by AerienA** [comment]
Fixed as of beta 2

**Comment by thornegoth** [comment]
still an issue for the following ethnicities:

- [ ] "caucasian_northern_blond"
- [ ] "Dunlending"
- [ ] "caucasian_northern_ginger"
- [ ] "Lossoth"
- [ ] "Noi Trevan"
- [ ] "Saralain"
- [ ] "Goblin"
- [ ] "Echo-Maker Goblin"
- [ ] "Sireshna"
- [ ] "East African"
- [ ] "Fariyin"
- [ ] "caucasian_northern_brown_hair"
